### ISSUE TITLE
Something is wrong with Global fonts

### ISSUE THREAD

**Issue by TheShark27** [676339784/kustom#1]
I have a problem. I've made a widget with a font global controlled by a function. If a switch is enabled the font will change to a custom one that I have downloaded (doesn't come installed). For some reason, in the preview the font doesn't show the correct font (it shows Roboto Bold instead), and sometimes even the widget on the homescreen doesn't. This is random, and I see no reason for it to have this behaviour. 
I think it's a bug, does anyone else have it?

**Comment by ineeee** [comment]
can confirm, i have it too

**Comment by 676339784** [comment]
@TheShark27 Which theme are you using?

**Comment by TheShark27** [comment]
@676339784 Sorry, I have forgotten to write it in the issue, but I'm on KWGT. The fonts I've been trying to use were Google Sans (which had always worked), Clock2017L (it's a font from Samsung's clock widget, it has initially worked but then it stopped), and Roboto Light (it has initially worked but then it has stopped).

**Comment by 676339784** [comment]
Out of curiosity, does this have to do with my themes?

**Comment by TheShark27** [comment]
@676339784 No, It doesn't. I was trying to make a widget with that feature.

**Comment by 676339784** [comment]
I'd recommend the homescreen threads or the [homescreen IRC channel](https://kiwiirc.com/client/irc.rizon.net/#homescreen): they'll be able to provide a better answer than I can. I don't interact with globals all that often.
